version: '3.5'
services:

  mongo:
    container_name: mongo
    image: mongo:4.2.8
    restart: always
    hostname: mongo
    environment:
      TZ: UTC # UTC, Europe/Amsterdam, America/Lima
      MONGO_INITDB_DATABASE: booking
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./files/mongo:/docker-entrypoint-initdb.d:ro
    command: mongod --bind_ip_all --replSet rs0
    networks:
      - zeebe_network

  mongo-setup:
    container_name: mongo-setup
    image: mongo:4.2.8
    restart: on-failure
    environment:
      MONGO_REPLICASET_HOST: "${MONGO_REPLICASET_HOST:-localhost}" # [localhost, mongo]
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./files/mongo-setup:/scripts
    entrypoint: [ "/scripts/setup-single.sh" ]
    networks:
      - zeebe_network
    depends_on:
      - mongo

networks:
  zeebe_network:
    external:
      name: zeebe_network
